services:
  ansible:
    build: .
    container_name: homelab-ansible
    working_dir: /ansible

    env_file:
      - .env

    volumes:
      - .:/ansible
      - ~/.ssh:/root/.ssh:ro
      - ./.ssh/known_hosts:/root/.ansible_known_hosts

    stdin_open: true
    tty: true
