---
proxmox:
  hosts:
    proxmox-server:
      ansible_host: "{{ lookup('env', 'PROXMOX_HOST') }}"

nextcloud:
  hosts:
    nextcloud-server:
      ansible_host: "{{ lookup('env', 'NEXTCLOUD_IP') }}"

pihole:
  hosts:
    pihole-server:
      ansible_host: "{{ lookup('env', 'PIHOLE_IP') }}"