---
proxmox:
  hosts:
    proxmox-server:
      ansible_host: "{{ lookup('env', 'PROXMOX_HOST') }}"

pihole:
  hosts:
    pihole-server:

traefik:
  hosts:
    traefik-server:

nextcloud:
  hosts:
    nextcloud-server:

ai:
  hosts:
    ai-server:

sandbox:
  hosts:
    sandbox-server:
