---
- name: Provision directories
  ansible.builtin.import_tasks: directories.yml

- name: Deploy application stack
  ansible.builtin.import_tasks: deploy.yml

- name: Configure application
  ansible.builtin.import_tasks: configure.yml
