---
- name: Check if LXC {{ lxc.vmid }} exists
  ansible.builtin.uri:
    url: "{{ proxmox_api_url }}/nodes/{{ proxmox_node }}/lxc/{{ lxc.vmid }}/config"
    method: GET
    headers:
      Authorization: "{{ proxmox_api_auth }}"
    validate_certs: false
    status_code:
      - 200
      - 500
    return_content: true
  register: proxmox_lxc_lookup
  no_log: true

- name: Build LXC creation parameters
  ansible.builtin.set_fact:
    lxc_create_body:
      vmid: "{{ lxc.vmid }}"
      hostname: "{{ lxc.hostname }}"
      ostemplate: "{{ proxmox_template_storage }}:vztmpl/{{ proxmox_template }}"
      storage: "{{ proxmox_lxc_storage }}"
      rootfs: "{{ proxmox_lxc_storage }}:{{ lxc.disk }}"
      cores: "{{ lxc.cores }}"
      memory: "{{ lxc.memory }}"
      swap: "{{ lxc.swap }}"
      net0: >-
        name=eth0,bridge={{ proxmox_bridge }},ip={{ lxc.ip }}/{{ lxc.cidr | default(proxmox_lxc_cidr) }},gw={{ lxc.gateway | default(proxmox_lxc_gateway) }}
      unprivileged: 1
      start: 1

- name: Add features to LXC creation parameters
  ansible.builtin.set_fact:
    lxc_create_body: "{{ lxc_create_body | combine({'features': lxc.features}) }}"
  when: lxc.features is defined

- name: Add data volume to LXC creation parameters
  ansible.builtin.set_fact:
    lxc_create_body: >-
      {{
        lxc_create_body | combine({
          'mp0': proxmox_lxc_storage ~ ':' ~ lxc.data_size ~ ',mp=' ~ lxc.data_mount
        })
      }}
  when:
    - lxc.data_size is defined

- name: Create LXC {{ lxc.vmid }}
  ansible.builtin.uri:
    url: "{{ proxmox_api_url }}/nodes/{{ proxmox_node }}/lxc"
    method: POST
    headers:
      Authorization: "{{ proxmox_api_auth }}"
    body_format: form-urlencoded
    body: "{{ lxc_create_body }}"
    status_code: 200
    return_content: true
    validate_certs: false
  when: proxmox_lxc_lookup.status != 200
  no_log: true

- name: Get LXC {{ lxc.vmid }} configuration
  ansible.builtin.command:
    cmd: "pct config {{ lxc.vmid }}"
  register: proxmox_lxc_config
  changed_when: false

- name: Add LXC {{ lxc.vmid }} data volume
  ansible.builtin.command:
    cmd: >
      pct set {{ lxc.vmid }}
      -mp0 {{ proxmox_lxc_storage }}:{{ lxc.data_size }},mp={{ lxc.data_mount }}
  when:
    - lxc.data_size is defined
    - "'mp0:' not in proxmox_lxc_config.stdout"
