---
- name: Create Proxmox API user
  ansible.builtin.import_playbook: create-api-user.yml

- name: Create Proxmox API token
  ansible.builtin.import_playbook: create-api-token.yml

- name: Grant Proxmox API permissions
  ansible.builtin.import_playbook: grant-api-permissions.yml
