---
- name: Get Proxmox infrastructure information
  hosts: proxmox
  connection: local
  gather_facts: false

  tasks:
    - name: Get nodes
      ansible.builtin.uri:
        url: "{{ proxmox_api_url }}/nodes"
        method: GET
        headers:
          Authorization: "{{ proxmox_api_auth }}"
        validate_certs: false
        return_content: true
      register: nodes
      no_log: true

    - name: Get storage
      ansible.builtin.uri:
        url: "{{ proxmox_api_url }}/nodes/{{ proxmox_node }}/storage"
        method: GET
        headers:
          Authorization: "{{ proxmox_api_auth }}"
        validate_certs: false
        return_content: true
      register: storage
      no_log: true

    - name: Get network
      ansible.builtin.uri:
        url: "{{ proxmox_api_url }}/nodes/{{ proxmox_node }}/network"
        method: GET
        headers:
          Authorization: "{{ proxmox_api_auth }}"
        validate_certs: false
        return_content: true
      register: network
      no_log: true

    - name: Show nodes
      ansible.builtin.debug:
        var: nodes.json.data

    - name: Show storage
      ansible.builtin.debug:
        var: storage.json.data

    - name: Show network
      ansible.builtin.debug:
        var: network.json.data

    - name: Get LXC templates
      ansible.builtin.uri:
        url: "{{ proxmox_api_url }}/nodes/{{ proxmox_node }}/storage/{{ proxmox_template_storage }}/content?content=vztmpl"
        method: GET
        headers:
          Authorization: "{{ proxmox_api_auth }}"
        validate_certs: false
        return_content: true
      register: templates
      no_log: true

    - name: Show LXC templates
      ansible.builtin.debug:
        var: templates.json.data
