---
- name: Test Proxmox API
  hosts: proxmox
  connection: local
  gather_facts: false

  tasks:
    - name: Validate Proxmox API configuration
      ansible.builtin.assert:
        that:
          - proxmox_host | length > 0
          - proxmox_api_user | length > 0
          - proxmox_api_token_id | length > 0
          - proxmox_api_token_secret | length > 0
        fail_msg: "Proxmox API environment variables are not configured."

    - name: Get Proxmox nodes
      ansible.builtin.uri:
        url: "{{ proxmox_api_url }}/nodes"
        method: GET
        headers:
          Authorization: "{{ proxmox_api_auth }}"
        validate_certs: false
        return_content: true
      register: proxmox_nodes
      no_log: true

    - name: Show Proxmox nodes
      ansible.builtin.debug:
        var: proxmox_nodes.json.data
