---
# Application configuration
nextcloud_ip: "{{ lookup('env', 'NEXTCLOUD_IP') }}"
nextcloud_db_name: "{{ lookup('env', 'NEXTCLOUD_DB_NAME') }}"
nextcloud_db_user: "{{ lookup('env', 'NEXTCLOUD_DB_USER') }}"
nextcloud_db_password: "{{ lookup('env', 'NEXTCLOUD_DB_PASSWORD') }}"
nextcloud_admin_user: "{{ lookup('env', 'NEXTCLOUD_ADMIN_USER') }}"
nextcloud_admin_password: "{{ lookup('env', 'NEXTCLOUD_ADMIN_PASSWORD') }}"
nextcloud_trusted_domains: "{{ lookup('env', 'NEXTCLOUD_IP') }}"
