---
pihole_version: "{{ lookup('env', 'PIHOLE_VERSION') }}"
pihole_upstream_dns: "{{ lookup('env', 'PIHOLE_UPSTREAM_DNS').split(',') }}"
pihole_admin_password: "{{ lookup('env', 'PIHOLE_ADMIN_PASSWORD') }}"
pihole_dhcp_start: "{{ lookup('env', 'PIHOLE_DHCP_START') }}"
pihole_dhcp_end: "{{ lookup('env', 'PIHOLE_DHCP_END') }}"
pihole_dhcp_router: "{{ lookup('env', 'PIHOLE_DHCP_ROUTER') }}"
pihole_dhcp_netmask: "{{ lookup('env', 'PIHOLE_DHCP_NETMASK') }}"
pihole_dhcp_lease_time: "{{ lookup('env', 'PIHOLE_DHCP_LEASE_TIME') }}"
pihole_dhcp_enabled: "{{ lookup('env', 'PIHOLE_DHCP_ENABLED') }}"